In [1]:
#Numbers and operations
a = 10
b = 3
print(a + b, a - b, a *b, a/b, a//b, a % b, a**b)

13 7 30 3.3333333333333335 3 1 1000


In [4]:
#Strings
s = "Machine Learning"
print(s.upper(), s.lower(), s[0:7], s.split())

MACHINE LEARNING machine learning Machine ['Machine', 'Learning']


In [5]:
#Lists
lst = [1, 2, 3, 4]
lst.append(5)
print(lst, lst[1:3])

[1, 2, 3, 4, 5] [2, 3]


In [7]:
#Dictionaries
d = {'name': 'Rijas', 'role': 'Intern'}
print(d['name'])

Rijas


In [10]:
#Loops and conditions
for i in range(5):
    if i % 2 == 0:
        print(f"{i} is even")

0 is even
2 is even
4 is even


In [11]:
#Functions
def greet (name):
    return f"Hello, {name}"
print(greet("Rijas"))

Hello, Rijas


In [12]:
import numpy as np
#creating arrays

In [16]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print("1D Array:", a)
print("2D Array:\n", b)

#Basic Math
print("Add :", a + 1)
print("Multiply:", a * 2)

#Useful properties
print("shape:", b.shape)
print("Data type:", b.dtype)

#Array of zeros and ones
z = np.zeros((2, 3))
o = np.ones((3, 2))
print("Zeros:\n", z)
print("Ones:\n", o)


#Random numbers
r = np.random.rand(2, 2)
print("Random 2*2 array:\n", r)

#Slicing and indexing
print("First element:", a[0])
print("Last row of b:", b[-1])

1D Array: [1 2 3]
2D Array:
 [[1 2]
 [3 4]]
Add : [2 3 4]
Multiply: [2 4 6]
shape: (2, 2)
Data type: int32
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Random 2*2 array:
 [[0.90585451 0.11954987]
 [0.84056853 0.51305398]]
First element: 1
Last row of b: [3 4]


In [19]:
#challenge
import numpy as np
a = np.random.randint(5, 21, (4, 4))
print(a)

[[19  5 14 13]
 [14 10 20 12]
 [17  9 10 10]
 [14 17 14 10]]


In [23]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)
print(arr[1:, 1:])
print(arr[:, 0])
print(arr[arr % 2 == 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[1 4 7]
[2 4 6 8]


In [25]:
marks = [89, 75, 92, 60]
print(marks[0])
print(marks[-1])
print(marks[1:3])
marks.append(88)

89
60
[75, 92]


In [26]:
print(marks[:])

[89, 75, 92, 60, 88]


In [27]:
print(marks[:3])

[89, 75, 92]


In [32]:
marks = [89, 75, 92, 60]
for mark in marks:
    if mark > 80:
        print("High:", mark)

High: 89
High: 92


In [33]:
def square(x):
    return x*x
print(square(5))

25


In [35]:
double = lambda x: x* 2
print(double(4))

8


In [37]:
people = [("Riya", 22), ("John", 19), ("Meera", 25), ("Aarav", 20)]
sorted_people = sorted(people, key = lambda x: x[1])
print(sorted_people)

[('John', 19), ('Aarav', 20), ('Riya', 22), ('Meera', 25)]


In [38]:
sorted_people = sorted(people, key = lambda x: x[1], reverse = True)
print(sorted_people)

[('Meera', 25), ('Riya', 22), ('Aarav', 20), ('John', 19)]


In [39]:
squares = []
for i in range(10):
    squares.append(i**2)
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [40]:
evens = [i for i in range(20) if i % 2 == 0]
print(evens)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [41]:
words = ["ai", "ml", "python"]
upper_words = [word.upper() for word in words]
print(upper_words)

['AI', 'ML', 'PYTHON']


In [45]:
numbers = [1, 2, 3, 4]
squared = map(lambda x: x**2, numbers)
print(list(squared))

[1, 4, 9, 16]


In [52]:
names = ["alice", "bob", "charlie"]
capitalized = list(map(lambda x: x.capitalize(), names))
print(capitalized)

['Alice', 'Bob', 'Charlie']


In [54]:
celsius = [0, 10, 20, 30, 40]
fahrenheit = list(map(lambda x: x * 9/5 + 32, celsius))
print(fahrenheit)

[32.0, 50.0, 68.0, 86.0, 104.0]


In [55]:
names = ["Alice", "Bob", "Anna", "Charlie", "Angela"]
a_names = list(filter(lambda x: x.startswith('A'), names))
print(a_names)               

['Alice', 'Anna', 'Angela']


In [59]:
from functools import reduce
numbers = [1, 2, 3, 4, 5, 6]
evens = list(filter(lambda x: x % 2 ==0, numbers))
product = reduce(lambda x, y: x*y, evens)
print(product)

48


In [61]:
students = [("Alice", 88), ("Bob", 75), ("Charlie", 95), ("David", 60)]
passed = list(filter(lambda student: student[1] > 80, students))
print(passed)

[('Alice', 88), ('Charlie', 95)]


In [62]:
names = ["alice", "bob", "charlie"]
capitalized = list(map(lambda x: x.capitalize(), names))
print(capitalized)

['Alice', 'Bob', 'Charlie']


In [64]:
students = [("Alice", 88), ("Bob", 75), ("Charlie", 95), ("David", 60)]
passed_students = list(filter(lambda x: x[1] >=80, students))
sort_passed = sorted(passed_students, reverse=True)
upper_names = list(map(lambda x: x[0].upper(), sort_passed))
print(upper_names)

['CHARLIE', 'ALICE']


In [65]:
t = (1, 2, 3)
print(t[1])

2


In [80]:
a = {1, 2, 3, 3, 5}
print(a)

{1, 2, 3, 5}


In [81]:
print(a)

{1, 2, 3, 5}


In [82]:
a.remove(5)

In [83]:
print(a)

{1, 2, 3}


In [84]:
a.add(4)

In [85]:
print(a)

{1, 2, 3, 4}


In [90]:
student = {"name": "Alice", "marks": 90}
print(student["name"])
student["grade"] = "A"

Alice


In [91]:
print(student)

{'name': 'Alice', 'marks': 90, 'grade': 'A'}


In [93]:
print(student["name"])

Alice


In [94]:
print(student["grade"])

A


In [95]:
student["age"] = 22

In [100]:
student["city"] = "Kochi"

In [101]:
print(student)

{'name': 'Alice', 'marks': 90, 'grade': 'A', 'age': 22, 'city': 'Kochi'}


In [103]:
del student["grade"]

In [104]:
for key, value in student.items():
    print(key, "->", value)

name -> Alice
marks -> 90
age -> 22
city -> Kochi


In [105]:
print(student["name"])

Alice


In [116]:
squares = {x: x**2 for x in range(1, 6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [119]:
file = open('sample.txt', 'r')
content = file.read()
print(content)
file.close()

Hello, this is the first line.
This is the second line.



In [118]:
import os
print(os.getcwd())

C:\Users\RijasTT\Documents\ml-prep


In [120]:
with open('sample.txt', 'r') as file:
    content = file.read()
    print(content)

Hello, this is the first line.
This is the second line.



In [124]:
with open('newfile.txt', 'w') as file:
    file.write("This is a new file.\nLine 2 added.")

In [125]:
with open('newfile.txt', 'r') as file:
    content = file.read()
    print(content)

This is a new file.
Line 2 added.


In [128]:
username = input("Enter your name: ")
with open('login_date', 'a') as log:
    log.write(f"user {username} logged in\n")

Enter your name:  Ijas
